#!/usr/bin/env python
"""Generate the typed Scala device catalog from the pinned LiteDRAM modules.py."""

import argparse
import importlib
import math
import pathlib
import sys
import types


TECHNOLOGY_TIMINGS = ["tREFI", "tWTR", "tCCD", "tRRD", "tZQCS"]
SPEEDGRADE_TIMINGS = ["tRP", "tRCD", "tWR", "tRFC", "tFAW", "tRAS"]
ABSTRACT_CLASSES = {
    "SDRAMModule", "SDRAMRegisteredModule", "SDRModule", "SDRRegisteredModule",
    "DDRModule", "DDRRegisteredModule", "LPDDRModule", "LPDDRRegisteredModule",
    "DDR2Module", "DDR2RegisteredModule", "DDR3Module", "DDR3RegisteredModule",
    "DDR4Module", "DDR4RegisteredModule",
}


def scala_number(value):
    value = float(value)
    if not math.isfinite(value):
        raise ValueError(f"non-finite catalog timing: {value}")
    text = repr(value)
    return text if "." in text or "e" in text.lower() else text + ".0"


def timing(value):
    if isinstance(value, tuple):
        cycles, nanoseconds = value
        cycles = 0 if cycles is None else int(cycles)
        nanoseconds = 0 if nanoseconds is None else nanoseconds
    else:
        cycles, nanoseconds = 0, value
    return f"SpdTiming({cycles}, {scala_number(nanoseconds)})"


def variants(value):
    if isinstance(value, dict):
        entries = [f'"{key}" -> {timing(item)}' for key, item in sorted(value.items())]
    else:
        entries = [f'"default" -> {timing(value)}']
    return "DramDeviceTiming(Map(" + ", ".join(entries) + "))"


def timing_map(settings, names):
    entries = []
    for name in names:
        value = getattr(settings, name, None)
        if value is not None:
            entries.append(f'"{name}" -> {variants(value)}')
    return "Map(" + ", ".join(entries) + ")"


def load_modules(reference):
    class Settings:
        def set_attributes(self, values):
            for key, value in values.items():
                if key != "self":
                    setattr(self, key, value)

    common = types.ModuleType("litedram.common")
    common.Settings = Settings
    common.GeomSettings = type("GeomSettings", (Settings,), {})
    common.TimingSettings = type("TimingSettings", (Settings,), {})
    sys.modules["litedram.common"] = common
    sys.path.insert(0, str(reference.parents[1]))
    return importlib.import_module("litedram.modules")


def render(reference):
    modules = load_modules(reference)
    devices = []
    for name, cls in vars(modules).items():
        if not isinstance(cls, type) or not issubclass(cls, modules.SDRAMModule):
            continue
        if name in ABSTRACT_CLASSES or not all(hasattr(cls, field)
            for field in ("memtype", "nbanks", "nrows", "ncols")):
            continue
        technology = timing_map(cls.technology_timings, TECHNOLOGY_TIMINGS)
        speedgrades = []
        for grade, values in sorted(cls.speedgrade_timings.items()):
            speedgrades.append(f'"{grade}" -> {timing_map(values, SPEEDGRADE_TIMINGS)}')
        bank_bits = int(cls.nbanks).bit_length() - 1
        row_bits = int(cls.nrows).bit_length() - 1
        column_bits = int(cls.ncols).bit_length() - 1
        device = (
            f'    DramDevice("{name}", "{cls.memtype}", '
            f'{str(bool(getattr(cls, "registered", False))).lower()}, '
            f'DramSpdGeometry({bank_bits}, {row_bits}, {column_bits}), '
            f'{technology}, Map({", ".join(speedgrades)}))'
        )
        devices.append(device)
    chunk_size = 8
    chunks = []
    chunk_names = []
    for index in range(0, len(devices), chunk_size):
        name = f"chunk{index // chunk_size}"
        chunk_names.append(f"{name}()")
        body = ",\n".join(devices[index:index + chunk_size])
        chunks.append(f"  private def {name}(): Seq[DramDevice] = Seq(\n{body})")
    return (
        "// Generated by scripts/generate_device_catalog.py; do not edit manually.\n"
        "package pleiadic.dram\n\n"
        "private[dram] object DramDeviceCatalogGenerated {\n"
        + "\n\n".join(chunks) + "\n\n"
        "  val devices: Seq[DramDevice] = " + " ++ ".join(chunk_names) + "\n"
        "}\n"
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--reference", type=pathlib.Path)
    args = parser.parse_args()
    root = pathlib.Path(__file__).resolve().parent.parent
    reference = args.reference or root.parents[1] / "litex/litedram/litedram/modules.py"
    output = root / "src/main/scala/pleiadic/dram/DramDeviceCatalogGenerated.scala"
    generated = render(reference.resolve())
    if args.check:
        if not output.exists() or output.read_text() != generated:
            raise SystemExit(f"generated catalog is stale: run {pathlib.Path(__file__).name}")
    else:
        output.write_text(generated)
        print(f"generated {output} from {reference}")


if __name__ == "__main__":
    main()
